services:
  jekyll:
      image: jekyll/jekyll:4.2.2
      user: "${UID:-1000}:${GID:-1000}"
      command: bash -c "bundle config set path 'vendor/bundle' && (bundle check || bundle install) && bundle exec jekyll serve -l --host 0.0.0.0"
      ports:
          - 4000:4000
          - 35729:35729
      volumes:
          - .:/srv/jekyll
