name: Test build (Jekyll)

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: Build the site in the jekyll/builder container
      run: |
        mkdir -p "${{ github.workspace }}/_site"
        docker run \
        --rm \
        --user "$(id -u):$(id -g)" \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/jekyll:4.2.2 /bin/bash -c "bundle config set path 'vendor/bundle' && (bundle check || bundle install) && bundle exec jekyll build --future"
